### ISSUE TITLE
Custom items JSON format example not updated to current spec

### ISSUE THREAD

**Issue by dgaxiola** [NaturalSelectionLabs/RSS3-Wiki#5]
File: [/src/rss3-sdk-for-javascript.md](https://github.com/NaturalSelectionLabs/RSS3-Wiki/tree/main/src)

The format for the JSON for custom items is not correct with the current JavaScript SDK version.

Current sample code shows: 
```
await rss3.items.custom.post({
    summary: 'I love RSS3',
    contents: [{
        type: 'image/jpeg',
        address: 'https://picsum.photos/200/300',
    }, {
        type: 'video/mp4',
        address: 'https://file-examples-com.github.io/uploads/2017/04/file_example_MP4_480_1_5MG.mp4',
    }],
});
```

The `type` property should be `mime_type` and the `address` property takes an array of strings instead of a single string, as per the current v0.3.1 spec: https://github.com/NaturalSelectionLabs/RSS3-Protocol/blob/main/versions/v0.3.1.md

It's probably worth reviewing all the sample to see if there's other out of date code.

**Comment by DIYgod** [comment]
Thanks. Fixed in fc66f508d9913bd91f92fd900fb08cdd45f50fd2
